Repository siwookim97/ecomm-hub, pull requests merged in 2023-06, with the labels that each got.

#16 fix: 메일 폼 수정 및 메일 Service 수정
  src/main/java/com/likelion/ecommhub/domain/MailDto.java
  src/main/java/com/likelion/ecommhub/service/MailService.java
  src/main/resources/static/resource/mailForm.css
  src/main/resources/static/resource/mailForm.js
  src/main/resources/static/resource/mailSent.css
  src/main/resources/templates/mailForm.html
  src/main/resources/templates/mailSent.html
  src/test/java/com/likelion/ecommhub/Service/MailServiceTest.java
Labels: 🔨fix, 🧪test

#17 Product Entity에 들어갈 Photo Entity 기능 구현
  src/main/java/com/likelion/ecommhub/domain/Photo.java
  src/main/java/com/likelion/ecommhub/repository/PhotoRepository.java
Labels: 🚀feature

#21 상품 등록기능 수정
  src/main/java/com/likelion/ecommhub/dto/ProductDto.java
  src/main/java/com/likelion/ecommhub/repository/MemberRepository.java
  src/main/java/com/likelion/ecommhub/service/MemberService.java
  src/main/java/com/likelion/ecommhub/service/ProductService.java
Labels: 🔨fix

#27 장바구니 페이지 구현
  build.gradle
  src/main/java/com/likelion/ecommhub/controller/CartController.java
  src/main/java/com/likelion/ecommhub/controller/MemberController.java
  src/main/java/com/likelion/ecommhub/domain/Cart.java
  src/main/java/com/likelion/ecommhub/domain/Member.java
  src/main/java/com/likelion/ecommhub/domain/Product.java
  src/main/java/com/likelion/ecommhub/dto/CartDto.java
  src/main/java/com/likelion/ecommhub/initData/NotProd.java
  src/main/java/com/likelion/ecommhub/repository/CartRepository.java
  src/main/java/com/likelion/ecommhub/repository/MemberRepository.java
  src/main/java/com/likelion/ecommhub/service/CartService.java
  src/main/java/com/likelion/ecommhub/service/MemberService.java
  src/main/resources/application.yml
  src/main/resources/templates/cartList.html
  src/main/resources/templates/member/seller-info.html
  src/test/java/com/likelion/ecommhub/Controller/CartControllerTest.java
Labels: 🚀feature

#29 fix: 장바구니 view 페이지 수정
  src/main/java/com/likelion/ecommhub/service/CartService.java
  src/main/java/com/likelion/ecommhub/service/MailService.java
  src/main/resources/application.yml
  src/main/resources/static/resource/style.css
  src/main/resources/templates/cartList.html
Labels: 🔨fix, 📄view

#30 상품 등록기능 고도화
  .gitignore
  src/main/java/com/likelion/ecommhub/controller/CartController.java
  src/main/java/com/likelion/ecommhub/controller/MemberController.java
  src/main/java/com/likelion/ecommhub/controller/ProductController.java
  src/main/java/com/likelion/ecommhub/domain/Cart.java
  src/main/java/com/likelion/ecommhub/domain/Gender.java
  src/main/java/com/likelion/ecommhub/domain/Image.java
  src/main/java/com/likelion/ecommhub/domain/Product.java
  src/main/java/com/likelion/ecommhub/dto/ProductDto.java
  src/main/java/com/likelion/ecommhub/initData/NotProd.java
  src/main/java/com/likelion/ecommhub/repository/ImageRepository.java
  src/main/java/com/likelion/ecommhub/repository/MemberRepository.java
  src/main/java/com/likelion/ecommhub/repository/PhotoRepository.java
  src/main/java/com/likelion/ecommhub/service/ImageService.java
  src/main/java/com/likelion/ecommhub/service/MemberService.java
  src/main/java/com/likelion/ecommhub/service/ProductService.java
  src/main/java/com/likelion/ecommhub/util/ImageStore.java
  src/main/resources/application.yml
  src/main/resources/templates/mailForm.html
  src/main/resources/templates/product/enroll.html
  src/main/resources/templates/product/home.html
  src/test/java/com/likelion/ecommhub/Controller/CartControllerTest.java
  src/test/java/com/likelion/ecommhub/Service/ProductServiceTest.java
  src/test/java/com/likelion/ecommhub/repository/ProductRepositoryTest.java
Labels: 🔨fix, 🚀feature, 🔥refactor

#32 제품 등록기능 View 페이지 수정
  src/main/java/com/likelion/ecommhub/controller/MailController.java
  src/main/java/com/likelion/ecommhub/dto/MailDto.java
  src/main/java/com/likelion/ecommhub/service/MailService.java
  src/main/resources/templates/product/enroll.html
  src/test/java/com/likelion/ecommhub/Service/MailServiceTest.java
Labels: 🚀feature, 📄view

#38 문의 기능 추가
  src/main/java/com/likelion/ecommhub/controller/InquiryController.java
  src/main/java/com/likelion/ecommhub/controller/ProductController.java
  src/main/java/com/likelion/ecommhub/domain/Cart.java
  src/main/java/com/likelion/ecommhub/domain/CartItem.java
  src/main/java/com/likelion/ecommhub/domain/Image.java
  src/main/java/com/likelion/ecommhub/domain/Inquiry.java
  src/main/java/com/likelion/ecommhub/domain/Member.java
  src/main/java/com/likelion/ecommhub/domain/Product.java
  src/main/java/com/likelion/ecommhub/dto/InquiryDto.java
  src/main/java/com/likelion/ecommhub/initData/NotProd.java
  src/main/java/com/likelion/ecommhub/repository/InquiryRepository.java
  src/main/java/com/likelion/ecommhub/service/ImageService.java
  src/main/java/com/likelion/ecommhub/service/InquiryService.java
  src/main/java/com/likelion/ecommhub/service/MemberService.java
  src/main/java/com/likelion/ecommhub/service/ProductService.java
Labels: 🚀feature

#43 리뷰 기능 추가
  src/main/java/com/likelion/ecommhub/controller/InquiryController.java
  src/main/java/com/likelion/ecommhub/controller/ReviewController.java
  src/main/java/com/likelion/ecommhub/domain/Cart.java
  src/main/java/com/likelion/ecommhub/domain/Member.java
  src/main/java/com/likelion/ecommhub/domain/Product.java
  src/main/java/com/likelion/ecommhub/domain/Review.java
  src/main/java/com/likelion/ecommhub/dto/ReviewDto.java
  src/main/java/com/likelion/ecommhub/repository/ReviewRepository.java
  src/main/java/com/likelion/ecommhub/service/InquiryService.java
  src/main/java/com/likelion/ecommhub/service/ReviewService.java
Labels: 🚀feature, 🔥refactor

#47 검색 기능 추가 #37
  src/main/java/com/likelion/ecommhub/controller/ProductController.java
  src/main/java/com/likelion/ecommhub/domain/Cart.java
  src/main/java/com/likelion/ecommhub/service/ProductService.java
  src/main/resources/templates/product/home.html
Labels: 🚀feature

#49 문의, 리뷰 페이지
  src/main/java/com/likelion/ecommhub/controller/InquiryController.java
  src/main/java/com/likelion/ecommhub/controller/ReviewController.java
  src/main/java/com/likelion/ecommhub/domain/Product.java
  src/main/java/com/likelion/ecommhub/initData/NotProd.java
  src/main/resources/templates/inquiry/enroll.html
  src/main/resources/templates/product/home.html
  src/main/resources/templates/review/enroll.html
Labels: 📄view

#50 시스템 공지사항 기능 추가 #25
  src/main/java/com/likelion/ecommhub/controller/NoticeController.java
  src/main/java/com/likelion/ecommhub/domain/Notice.java
  src/main/java/com/likelion/ecommhub/domain/NoticeType.java
  src/main/java/com/likelion/ecommhub/dto/NoticeDto.java
  src/main/java/com/likelion/ecommhub/repository/NoticeRepository.java
  src/main/java/com/likelion/ecommhub/service/NoticeService.java
  src/main/resources/templates/notice/edit-form.html
  src/main/resources/templates/notice/form.html
  src/main/resources/templates/notice/list.html
  src/test/java/com/likelion/ecommhub/Service/NoticeServiceTest.java
  src/test/java/com/likelion/ecommhub/repository/NoticeRepositoryTest.java
Labels: 🚀feature, 🧪test, 📄view

#54 Chart page
  src/main/java/com/likelion/ecommhub/controller/SalesController.java
  src/main/java/com/likelion/ecommhub/domain/Sales.java
  src/main/java/com/likelion/ecommhub/dto/CartDto.java
  src/main/java/com/likelion/ecommhub/dto/SalesDto.java
  src/main/java/com/likelion/ecommhub/repository/SalesRepository.java
  src/main/java/com/likelion/ecommhub/service/SalesService.java
  src/main/resources/application.yml
  src/main/resources/templates/ChartPage.html
Labels: 🚀feature, 📄view

#57 Chart page
  src/main/java/com/likelion/ecommhub/controller/SalesController.java
  src/main/java/com/likelion/ecommhub/domain/Sales.java
  src/main/java/com/likelion/ecommhub/dto/SalesDto.java
  src/main/java/com/likelion/ecommhub/service/SalesService.java
  src/main/resources/templates/ChartPage.html
  src/main/resources/templates/monthly-sales.html
Labels: 🔨fix, 📄view

#61 검색 기능 동적쿼리 도입
  build.gradle
  src/main/java/com/likelion/ecommhub/controller/MemberController.java
  src/main/java/com/likelion/ecommhub/controller/NoticeController.java
  src/main/java/com/likelion/ecommhub/controller/ProductController.java
  src/main/java/com/likelion/ecommhub/dto/ProductSearchCondition.java
  src/main/java/com/likelion/ecommhub/dto/ProductSearchResult.java
  src/main/java/com/likelion/ecommhub/initData/NotProd.java
  src/main/java/com/likelion/ecommhub/repository/ProductRepository.java
  src/main/java/com/likelion/ecommhub/repository/ProductRepositoryCustom.java
  src/main/java/com/likelion/ecommhub/repository/ProductRepositoryImpl.java
  src/main/java/com/likelion/ecommhub/service/ProductService.java
  src/main/resources/templates/product/home.html
  src/main/resources/templates/product/search.html
Labels: 🚀feature

#62 매출 통계, 장바구니 수정
  src/main/java/com/likelion/ecommhub/service/CartService.java
  src/main/resources/application.yml
  src/main/resources/templates/cart.html
  src/main/resources/templates/monthly-sales.html
Labels: 🔨fix, 📄view

#66 장바구니 삭제 기능 오류 수정
  src/main/java/com/likelion/ecommhub/service/CartService.java
  src/main/resources/templates/cart.html
Labels: 🔨fix

#68 검색 기능 고도화
  src/main/java/com/likelion/ecommhub/controller/ProductController.java
  src/main/java/com/likelion/ecommhub/dto/ProductSearchCondition.java
  src/main/java/com/likelion/ecommhub/dto/ProductSearchResult.java
  src/main/java/com/likelion/ecommhub/repository/ProductRepositoryCustom.java
  src/main/java/com/likelion/ecommhub/repository/ProductRepositoryImpl.java
  src/main/java/com/likelion/ecommhub/service/ProductService.java
  src/main/resources/templates/product/home.html
  src/main/resources/templates/product/search.html
Labels: 🔨fix, 🚀feature, 📄view

#70 구매 버튼 클릭시 결제 진행 및 주문 내역 업데이트
  build.gradle
  src/main/java/com/likelion/ecommhub/config/JpaConfig.java
  src/main/java/com/likelion/ecommhub/controller/CartController.java
  src/main/java/com/likelion/ecommhub/controller/OrderController.java
  src/main/java/com/likelion/ecommhub/domain/Cart.java
  src/main/java/com/likelion/ecommhub/domain/CartItem.java
  src/main/java/com/likelion/ecommhub/domain/Member.java
  src/main/java/com/likelion/ecommhub/domain/Order.java
  src/main/java/com/likelion/ecommhub/domain/OrderItem.java
  src/main/java/com/likelion/ecommhub/domain/Product.java
  src/main/java/com/likelion/ecommhub/dto/MemberJoinDto.java
  src/main/java/com/likelion/ecommhub/initData/NotProd.java
  src/main/java/com/likelion/ecommhub/repository/OrderItemRepository.java
  src/main/java/com/likelion/ecommhub/service/CartService.java
  src/main/java/com/likelion/ecommhub/service/MemberService.java
  src/main/java/com/likelion/ecommhub/service/OrderService.java
  src/main/resources/templates/cart.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/orderList.html
  src/test/java/com/likelion/ecommhub/Service/ProductServiceTest.java
  src/test/java/com/likelion/ecommhub/repository/MemberRepositoryTest.java
Labels: 🔨fix, 🚀feature, 🔥refactor

#75 페이지 UI 템플릿 맞추기 & Rq 클래스 도입
  build.gradle
  src/main/java/com/likelion/ecommhub/config/auth/AuthenticationConfig.java
  src/main/java/com/likelion/ecommhub/controller/CartController.java
  src/main/java/com/likelion/ecommhub/controller/MemberController.java
  src/main/java/com/likelion/ecommhub/util/Rq.java
  src/main/java/com/likelion/ecommhub/util/RsData.java
  src/main/java/com/likelion/ecommhub/util/Ut.java
  src/main/resources/application.yml
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/main/resources/messages_ko.properties
  src/main/resources/static/resource/common/common.css
  src/main/resources/static/resource/common/common.js
  src/main/resources/templates/common/js.html
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/error/404.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/member/join.html
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/seller-info.html
  src/main/resources/templates/usr/layout/layout.html
  src/main/resources/templates/usr/member/cart.html
  src/main/resources/templates/usr/member/cartAdd.html
  src/main/resources/templates/usr/member/join.html
  src/main/resources/templates/usr/member/joinBuyer.html
  src/main/resources/templates/usr/member/login.html
  src/main/resources/templates/usr/member/loginSuccess.html
  src/main/resources/templates/usr/member/seller-info.html
Labels: 🔨fix, 🚀feature, 📄view

#76 이미지 저장을 위해 AWS S3 도입
  build.gradle
  src/main/java/com/likelion/ecommhub/config/S3Config.java
  src/main/java/com/likelion/ecommhub/controller/ProductController.java
  src/main/java/com/likelion/ecommhub/domain/Image.java
  src/main/java/com/likelion/ecommhub/repository/ImageRepository.java
  src/main/java/com/likelion/ecommhub/service/ImageService.java
  src/main/java/com/likelion/ecommhub/util/ImageStore.java
  src/main/resources/templates/product/home.html
Labels: 🚀feature, 🔥refactor

#81 Product 엔티티와 Image 엔티티 연관관계 리팩토링
  build.gradle
  src/main/java/com/likelion/ecommhub/controller/ProductController.java
  src/main/java/com/likelion/ecommhub/domain/Image.java
  src/main/java/com/likelion/ecommhub/domain/Product.java
  src/main/java/com/likelion/ecommhub/dto/ProductDto.java
  src/main/java/com/likelion/ecommhub/dto/ProductSearchResult.java
  src/main/java/com/likelion/ecommhub/repository/ProductRepositoryImpl.java
  src/main/java/com/likelion/ecommhub/service/ImageService.java
  src/main/java/com/likelion/ecommhub/util/Ut.java
  src/main/resources/templates/product/enroll.html
  src/main/resources/templates/product/home.html
Labels: 🔥refactor

#78 사용자 정보 & 수정 기능
  src/main/java/com/likelion/ecommhub/controller/MemberController.java
  src/main/java/com/likelion/ecommhub/controller/OrderController.java
  src/main/java/com/likelion/ecommhub/domain/Cart.java
  src/main/java/com/likelion/ecommhub/domain/Member.java
  src/main/java/com/likelion/ecommhub/domain/Order.java
  src/main/java/com/likelion/ecommhub/repository/MemberRepository.java
  src/main/java/com/likelion/ecommhub/service/MemberService.java
  src/main/java/com/likelion/ecommhub/util/Ut.java
  src/main/resources/application.yml
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/usr/member/memberModify.html
  src/main/resources/templates/usr/member/memberPage.html
  src/main/resources/templates/usr/member/seller-info.html
  src/test/java/com/likelion/ecommhub/repository/MemberRepositoryTest.java
  src/test/java/com/likelion/ecommhub/service/MemberServiceTest.java
Labels: 🚀feature, 📄view

#83 UI 템플릿 맞추기 & 에러 alert 띄우기
  src/main/java/com/likelion/ecommhub/controller/MemberController.java
  src/main/java/com/likelion/ecommhub/service/MemberService.java
  src/main/resources/messages.properties
  src/main/resources/templates/monthly-sales.html
  src/main/resources/templates/notice/list.html
  src/main/resources/templates/product/home.html
  src/main/resources/templates/usr/layout/layout.html
  src/main/resources/templates/usr/member/join.html
  src/main/resources/templates/usr/member/login.html
  src/main/resources/templates/usr/member/loginSuccess.html
Labels: 🚀feature, 🔥refactor, 📄view

#84 제품 상세 페이지 구현
  build.gradle
  src/main/java/com/likelion/ecommhub/controller/CartController.java
  src/main/java/com/likelion/ecommhub/controller/MemberController.java
  src/main/java/com/likelion/ecommhub/controller/ProductController.java
  src/main/java/com/likelion/ecommhub/repository/ReviewRepository.java
  src/main/java/com/likelion/ecommhub/service/CartService.java
  src/main/java/com/likelion/ecommhub/service/ReviewService.java
  src/main/resources/static/resource/style.css
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/product/enroll.html
  src/main/resources/templates/product/productView.html
  src/main/resources/templates/review/enroll.html
  src/main/resources/templates/usr/member/cart.html
  src/main/resources/templates/usr/member/memberPage.html
Labels: 🚀feature, 🔥refactor, 📄view

#87 merge 과정에서 발생한 build 문제 수정
  src/main/java/com/likelion/ecommhub/config/auth/AuthenticationConfig.java
  src/main/java/com/likelion/ecommhub/controller/CartController.java
  src/main/java/com/likelion/ecommhub/controller/MemberController.java
  src/main/java/com/likelion/ecommhub/controller/NoticeController.java
  src/main/java/com/likelion/ecommhub/controller/ProductController.java
  src/main/java/com/likelion/ecommhub/domain/Member.java
  src/main/java/com/likelion/ecommhub/dto/MemberJoinDto.java
  src/main/java/com/likelion/ecommhub/initData/NotProd.java
  src/main/java/com/likelion/ecommhub/service/MemberService.java
  src/main/resources/templates/usr/member/join.html
  src/main/resources/templates/usr/member/loginSuccess.html
Labels: 🔨fix

#92 url에 사용자 id 숨김, 권한 설정
  src/main/java/com/likelion/ecommhub/controller/OrderController.java
  src/main/java/com/likelion/ecommhub/controller/ProductController.java
  src/main/java/com/likelion/ecommhub/service/MemberService.java
  src/main/resources/templates/fragments/header.html
Labels: 🔨fix

#91 장바구니 url 수정 &구매하기 버튼 기능
  src/main/java/com/likelion/ecommhub/controller/CartController.java
  src/main/java/com/likelion/ecommhub/service/MemberService.java
  src/main/java/com/likelion/ecommhub/service/ProductService.java
  src/main/resources/templates/usr/member/cart.html
Labels: 🔨fix

#95 MemberController 권한 수정, myPage 작동하지 않는 문제 수정
  src/main/java/com/likelion/ecommhub/config/auth/AuthenticationConfig.java
  src/main/java/com/likelion/ecommhub/controller/MemberController.java
  src/main/java/com/likelion/ecommhub/controller/ProductController.java
  src/main/java/com/likelion/ecommhub/domain/Member.java
  src/main/java/com/likelion/ecommhub/service/MemberService.java
  src/main/java/com/likelion/ecommhub/service/OrderService.java
  src/main/resources/templates/usr/member/memberModify.html
  src/main/resources/templates/usr/member/memberPage.html
Labels: 🔨fix

#96 상세보기 버튼, 메인페이지로 redirect
  src/main/java/com/likelion/ecommhub/controller/HomeController.java
  src/main/resources/static/resource/seller-info.css
  src/main/resources/templates/product/home.html
Labels: 🔥refactor

#98 enroll, myPage UI 수정
  src/main/resources/templates/inquiry/enroll.html
  src/main/resources/templates/product/enroll.html
  src/main/resources/templates/product/productView.html
  src/main/resources/templates/review/enroll.html
  src/main/resources/templates/usr/member/memberPage.html
Labels: 🔥refactor, 📄view

#100 notice 권한 설정
  src/main/java/com/likelion/ecommhub/controller/NoticeController.java
  src/main/java/com/likelion/ecommhub/domain/MemberRole.java
  src/main/java/com/likelion/ecommhub/initData/NotProd.java
  src/main/resources/templates/notice/list.html
  src/main/resources/templates/orderList.html
  src/main/resources/templates/usr/member/memberModify.html
  src/main/resources/templates/usr/member/memberPage.html
Labels: 🔥refactor

#101 프로젝트 전체적인 코드 스타일, 권한 수정
  src/main/java/com/likelion/ecommhub/controller/CartController.java
  src/main/java/com/likelion/ecommhub/controller/OrderController.java
  src/main/java/com/likelion/ecommhub/controller/SalesController.java
  src/main/java/com/likelion/ecommhub/domain/Inquiry.java
  src/main/java/com/likelion/ecommhub/domain/Notice.java
  src/main/java/com/likelion/ecommhub/domain/Order.java
  src/main/java/com/likelion/ecommhub/dto/MemberLoginDto.java
  src/main/java/com/likelion/ecommhub/dto/ProductSearchCondition.java
  src/main/java/com/likelion/ecommhub/dto/ProductSearchResult.java
  src/main/java/com/likelion/ecommhub/dto/SalesDto.java
  src/main/java/com/likelion/ecommhub/repository/CartRepository.java
  src/main/java/com/likelion/ecommhub/service/CartService.java
  src/main/java/com/likelion/ecommhub/service/ImageService.java
  src/main/java/com/likelion/ecommhub/service/MailService.java
  src/main/java/com/likelion/ecommhub/service/MemberService.java
  src/main/java/com/likelion/ecommhub/service/ReviewService.java
  src/main/java/com/likelion/ecommhub/service/SalesService.java
  src/main/resources/messages.properties
  src/main/resources/templates/orderList.html
  src/main/resources/templates/product/productView.html
  src/main/resources/templates/usr/layout/layout.html
Labels: 🔨fix, 🔥refactor

#103 제품상세페이지에서 모달띄워주기
  src/main/java/com/likelion/ecommhub/controller/CartController.java
  src/main/resources/static/resource/common/common.js
  src/main/resources/templates/product/productView.html
  src/main/resources/templates/usr/member/cart.html
Labels: 🔥refactor, 📄view

#106 Seller일 경우에만 Add Product 보이도록 수정
  src/main/resources/templates/product/home.html
  src/main/resources/templates/product/productView.html
  src/main/resources/templates/usr/member/cartAdd.html
Labels: 🔥refactor, 📄view

#108 네비게이션 바 폼 리팩토링
  src/main/java/com/likelion/ecommhub/controller/HomeController.java
  src/main/resources/templates/usr/layout/layout.html
  src/main/resources/templates/usr/member/test.html
Labels: 🔥refactor

#111 네비게이션바 수정
  src/main/resources/templates/usr/layout/layout.html
Labels: 🔥refactor

#112 footer 적용
  src/main/resources/static/resource/style.css
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/orderList.html
  src/main/resources/templates/usr/layout/layout.html
  src/main/resources/templates/usr/member/cart.html
Labels: 🔥refactor

#115 네비게이션 바 폼 추가수정
  src/main/resources/templates/usr/member/join.html
  src/main/resources/templates/usr/member/joinBuyer.html
  src/main/resources/templates/usr/member/joinSeller.html
  src/main/resources/templates/usr/member/login.html
Labels: 🔥refactor

#116 403,500 에러 페이지 구현, 네비게이션 바에서 상품 검색할 수 있게 수정
  src/main/resources/templates/error/403.html
  src/main/resources/templates/error/500.html
  src/main/resources/templates/usr/layout/layout.html
Labels: 🚀feature, 🔥refactor

#119 home view수정
  src/main/resources/templates/product/home.html
  src/main/resources/templates/usr/layout/layout.html
Labels: 🔥refactor, 📄view

#121 제품 상세, 문의, 리뷰 view 수정, footer 수정
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/inquiry/enroll.html
  src/main/resources/templates/product/productView.html
  src/main/resources/templates/review/enroll.html
  src/main/resources/templates/usr/layout/layout.html
Labels: 🔥refactor, 📄view

#122 구매기능 오류 수정
  src/main/java/com/likelion/ecommhub/controller/CartController.java
  src/main/java/com/likelion/ecommhub/controller/OrderController.java
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/usr/member/cart.html
  src/main/resources/templates/usr/member/orderList.html
Labels: 🔨fix

#123 제품 페이지 폼 수정
  src/main/resources/templates/product/home.html
Labels: 🔥refactor, 📄view

#128 상품 정렬 로직&UI 수정
  src/main/java/com/likelion/ecommhub/repository/ProductRepositoryImpl.java
  src/main/resources/templates/product/home.html
Labels: 🔥refactor, 📄view

#130 네비게이션 바 장바구니 버튼 추가, 검색 로직 변경
  src/main/java/com/likelion/ecommhub/dto/ProductSearchCondition.java
  src/main/java/com/likelion/ecommhub/repository/ProductRepositoryImpl.java
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/product/home.html
  src/main/resources/templates/usr/layout/layout.html
Labels: 🔥refactor, 📄view

#132 하단 바 글자 흰색으로 통일
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/notice/edit-form.html
  src/main/resources/templates/notice/form.html
  src/main/resources/templates/notice/list.html
  src/main/resources/templates/product/enroll.html
  src/main/resources/templates/product/productView.html
  src/main/resources/templates/usr/layout/layout.html
  src/main/resources/templates/usr/member/cart.html
  src/main/resources/templates/usr/member/joinBuyer.html
  src/main/resources/templates/usr/member/joinSeller.html
  src/main/resources/templates/usr/member/login.html
  src/main/resources/templates/usr/member/memberModify.html
  src/main/resources/templates/usr/member/memberPage.html
  src/main/resources/templates/usr/member/orderList.html
Labels: 🔥refactor, 📄view

#133 회원 정보 수정 URL과 DTO 도입
  src/main/java/com/likelion/ecommhub/controller/MemberController.java
  src/main/java/com/likelion/ecommhub/dto/MemberModifyDto.java
  src/main/java/com/likelion/ecommhub/service/MemberService.java
  src/main/resources/templates/usr/member/memberModify.html
  src/main/resources/templates/usr/member/memberPage.html
Labels: 🔨fix, 🚀feature, 🔥refactor

#136 구매하기 버튼 클릭 후 주문 내역으로 이동
  src/main/resources/templates/usr/member/cart.html
Labels: 🔥refactor, 📄view

#140 구매자 회원가입 후 장바구니 접속이 안되는 오류, 구매하고 주문 내역 갱신되지 않음(새로고침 필요) 수정
  src/main/java/com/likelion/ecommhub/controller/OrderController.java
  src/main/java/com/likelion/ecommhub/service/MemberService.java
  src/main/resources/templates/usr/member/cart.html
  src/main/resources/templates/usr/member/orderList.html
Labels: 🔨fix

#142 장바구니 UI 수정
  src/main/resources/templates/usr/member/cart.html
Labels: 📄view

#143 판매자 마이페이지 수정, 매출액 동적 연결, 상세페이지 장바구니 오류 수정
  src/main/java/com/likelion/ecommhub/controller/CartController.java
  src/main/java/com/likelion/ecommhub/controller/OrderController.java
  src/main/java/com/likelion/ecommhub/controller/SalesController.java
  src/main/java/com/likelion/ecommhub/domain/Member.java
  src/main/java/com/likelion/ecommhub/domain/Sales.java
  src/main/java/com/likelion/ecommhub/initData/NotProd.java
  src/main/java/com/likelion/ecommhub/repository/SalesRepository.java
  src/main/java/com/likelion/ecommhub/service/OrderService.java
  src/main/java/com/likelion/ecommhub/service/SalesService.java
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/monthly-sales.html
  src/main/resources/templates/product/productView.html
  src/main/resources/templates/usr/member/memberPage.html
Labels: 🔨fix, 🔥refactor

#146 회원 정보 수정 form 변경
  src/main/java/com/likelion/ecommhub/dto/MemberModifyDto.java
  src/main/resources/templates/usr/member/memberModify.html
Labels: 🔥refactor, 📄view

#148 공지 사항 연결
  src/main/java/com/likelion/ecommhub/initData/NotProd.java
  src/main/resources/templates/notice/list.html
  src/main/resources/templates/usr/layout/layout.html
Labels: 📄view

#149 리뷰 검증로직 추가, 회원 수정 폼 변경
  src/main/java/com/likelion/ecommhub/controller/MemberController.java
  src/main/java/com/likelion/ecommhub/controller/ProductController.java
  src/main/java/com/likelion/ecommhub/controller/ReviewController.java
  src/main/java/com/likelion/ecommhub/domain/Member.java
  src/main/java/com/likelion/ecommhub/dto/MemberModifyDto.java
  src/main/java/com/likelion/ecommhub/repository/ReviewRepository.java
  src/main/java/com/likelion/ecommhub/service/MemberService.java
  src/main/java/com/likelion/ecommhub/service/ReviewService.java
  src/main/resources/templates/product/home.html
  src/main/resources/templates/usr/member/memberModify.html
Labels: 🔥refactor, 📄view

#154 제품 상세 페이지 UI 수정, 제품 등록
  src/main/java/com/likelion/ecommhub/controller/MemberController.java
  src/main/java/com/likelion/ecommhub/controller/ReviewController.java
  src/main/resources/templates/product/enroll.html
  src/main/resources/templates/product/home.html
  src/main/resources/templates/product/productView.html
  src/main/resources/templates/usr/member/sellerInfo.html
Labels: 📄view

#156 공지사항 UI 변경
  src/main/resources/templates/notice/form.html
  src/main/resources/templates/notice/list.html
Labels: 📄view

#158 매출통계 UI 수정
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/monthly-sales.html
  src/main/resources/templates/usr/layout/layout.html
Labels: 🔥refactor, 📄view

#159 리뷰 등록, 문의 등록 view 수정, 검증
  src/main/java/com/likelion/ecommhub/controller/ErrorController.java
  src/main/java/com/likelion/ecommhub/controller/InquiryController.java
  src/main/java/com/likelion/ecommhub/controller/MemberController.java
  src/main/java/com/likelion/ecommhub/service/ReviewService.java
  src/main/java/com/likelion/ecommhub/util/GlobalExceptionHandler.java
  src/main/resources/templates/inquiry/enroll.html
  src/main/resources/templates/review/enroll.html
Labels: 🔥refactor, 📄view

#162 판매자 UI 변경
  src/main/resources/templates/notice/edit-form.html
  src/main/resources/templates/usr/member/memberPage.html
Labels: 📄view

#164 네비바에 매출통계 (판매자권한설정) 들어갈수있게
  src/main/java/com/likelion/ecommhub/controller/SalesController.java
  src/main/resources/templates/usr/layout/layout.html
  src/main/resources/templates/usr/member/monthly-sales.html
Labels: 🔥refactor, 📄view

#166 제품상세페이지에서 장바구니에 담을 때 모달이 뜨지 않고 바로 장바구니로 이동하게 수정
  src/main/resources/templates/product/productView.html
Labels: 🔨fix, 📄view

#173 Fix 172
  src/main/java/com/likelion/ecommhub/controller/SalesController.java
  src/main/java/com/likelion/ecommhub/repository/SalesRepository.java
  src/main/java/com/likelion/ecommhub/service/SalesService.java
  src/main/resources/templates/usr/member/monthly-sales.html
Labels: 🔨fix, 📄view

#170 장바구니 페이지 수정
  src/main/java/com/likelion/ecommhub/controller/CartController.java
  src/main/java/com/likelion/ecommhub/controller/OrderController.java
  src/main/java/com/likelion/ecommhub/service/CartService.java
  src/main/java/com/likelion/ecommhub/service/MemberService.java
  src/main/resources/templates/usr/member/cart.html
Labels: 🔨fix

#174 문의 페이지 생성
  src/main/java/com/likelion/ecommhub/controller/InquiryController.java
  src/main/java/com/likelion/ecommhub/controller/MemberController.java
  src/main/java/com/likelion/ecommhub/controller/ProductController.java
  src/main/java/com/likelion/ecommhub/repository/InquiryRepository.java
  src/main/java/com/likelion/ecommhub/service/InquiryService.java
  src/main/resources/templates/inquiry/view.html
  src/main/resources/templates/usr/member/sellerInfo.html
Labels: 📄view

#175 리뷰/문의 버튼 이동 구현
  src/main/resources/templates/usr/member/memberPage.html
Labels: 📄view

#178 mail폼 mailto: 로 변경
  src/main/java/com/likelion/ecommhub/controller/MailController.java
  src/main/java/com/likelion/ecommhub/dto/MailDto.java
  src/main/java/com/likelion/ecommhub/service/MailService.java
  src/main/resources/static/resource/mailForm.css
  src/main/resources/static/resource/mailForm.js
  src/main/resources/static/resource/mailSent.css
  src/main/resources/templates/mailForm.html
  src/main/resources/templates/mailSent.html
  src/main/resources/templates/usr/member/memberPage.html
  src/test/java/com/likelion/ecommhub/Service/MailServiceTest.java
Labels: 🚀feature, 📄view

#182 마이페이지 주문내역 오류 수정
  src/main/java/com/likelion/ecommhub/controller/MemberController.java
  src/main/java/com/likelion/ecommhub/controller/OrderController.java
  src/main/resources/templates/usr/member/memberPage.html
Labels: 🔨fix, 📄view

#183 최종: 코드 컨벤션
  src/main/java/com/likelion/ecommhub/controller/CartController.java
  src/main/java/com/likelion/ecommhub/controller/HomeController.java
  src/main/java/com/likelion/ecommhub/controller/NoticeController.java
  src/main/java/com/likelion/ecommhub/controller/OrderController.java
  src/main/java/com/likelion/ecommhub/controller/SalesController.java
  src/main/java/com/likelion/ecommhub/domain/CartItem.java
  src/main/java/com/likelion/ecommhub/domain/Member.java
  src/main/java/com/likelion/ecommhub/domain/MemberRole.java
  src/main/java/com/likelion/ecommhub/domain/Order.java
  src/main/java/com/likelion/ecommhub/domain/OrderItem.java
  src/main/java/com/likelion/ecommhub/domain/Sales.java
  src/main/java/com/likelion/ecommhub/dto/SalesDto.java
  src/main/java/com/likelion/ecommhub/initData/NotProd.java
  src/main/java/com/likelion/ecommhub/repository/CartRepository.java
  src/main/java/com/likelion/ecommhub/repository/NoticeRepository.java
  src/main/java/com/likelion/ecommhub/repository/OrderItemRepository.java
  src/main/java/com/likelion/ecommhub/repository/OrderRepository.java
  src/main/java/com/likelion/ecommhub/repository/ProductRepositoryImpl.java
  src/main/java/com/likelion/ecommhub/repository/ReviewRepository.java
  src/main/java/com/likelion/ecommhub/repository/SalesRepository.java
  src/main/java/com/likelion/ecommhub/service/CartService.java
  src/main/java/com/likelion/ecommhub/service/ImageService.java
  src/main/java/com/likelion/ecommhub/service/MemberService.java
  src/main/java/com/likelion/ecommhub/service/NoticeService.java
  src/main/java/com/likelion/ecommhub/service/OrderService.java
  src/main/java/com/likelion/ecommhub/service/ProductService.java
  src/main/java/com/likelion/ecommhub/service/SalesService.java
  src/main/resources/application-secret.yml.default
  src/main/resources/messages.properties
  src/main/resources/messages_ko.properties
  src/main/resources/templates/common/js.html
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/error/400.html
  src/main/resources/templates/error/403.html
  src/main/resources/templates/error/404.html
  src/main/resources/templates/error/500.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/inquiry/view.html
  src/main/resources/templates/notice/edit-form.html
  src/main/resources/templates/notice/form.html
  src/main/resources/templates/notice/list.html
  src/main/resources/templates/product/home.html
  src/main/resources/templates/product/productView.html
  src/main/resources/templates/usr/layout/layout.html
  src/main/resources/templates/usr/member/cart.html
  src/main/resources/templates/usr/member/join.html
  src/main/resources/templates/usr/member/joinSeller.html
  src/main/resources/templates/usr/member/login.html
  src/main/resources/templates/usr/member/memberModify.html
  src/main/resources/templates/usr/member/memberPage.html
  src/main/resources/templates/usr/member/monthly-sales.html
  src/main/resources/templates/usr/member/test.html
  src/test/java/com/likelion/ecommhub/Service/NoticeServiceTest.java
  src/test/java/com/likelion/ecommhub/Service/ProductServiceTest.java
  src/test/java/com/likelion/ecommhub/repository/MemberRepositoryTest.java
  src/test/java/com/likelion/ecommhub/repository/NoticeRepositoryTest.java
  src/test/java/com/likelion/ecommhub/repository/ProductRepositoryTest.java
  src/test/java/com/likelion/ecommhub/service/MemberServiceTest.java
Labels: 🔨fix

#186 fix: 제품 상세 페이지
  src/main/resources/templates/product/productView.html
  src/main/resources/templates/usr/member/memberPage.html
Labels: 🔨fix

#188 매출통계 합산오류 수정
  src/main/java/com/likelion/ecommhub/controller/OrderController.java
  src/main/java/com/likelion/ecommhub/service/SalesService.java
  src/main/resources/templates/usr/member/memberPage.html
Labels: 🔨fix
